repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-ensure-ascii, --no-sort-keys]
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-added-large-files
      - id: detect-private-key

  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.74.1
  #   hooks:
  #     - id: terraform_docs
  #     - id: terraform_fmt
  #     - id: terraform_tflint
  #       args:
  #         - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
