---
repos:
  - repo: local
    hooks:
      - id: prettier
        name: Prettier Formatter
        entry: >
          bash -c 'git diff --name-only --cached --diff-filter=ACM
          | grep -E "\.(json|ya?ml|md|js|ts)$"
          | xargs prettier --write'
        language: system
        pass_filenames: false

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - --format=parsable
          - --strict

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=4
          - --no-ensure-ascii
          - --no-sort-keys

      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials

      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.3
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true

      - id: terraform_fmt

      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
