---
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: stage-yaml-fixes
        name: Stage YAML Fixes
        language: system
        entry: bash -c 'git diff --name-only --cached --diff-filter=ACM | grep -E "\.(ya?ml)$" | xargs
          -r git add'
        pass_filenames: false
        stages: [pre-commit]
        require_serial: true
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
        args: ["-conf=.yamlfmt.yaml"]
        stages: [pre-commit]
        require_serial: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-ensure-ascii, --no-sort-keys]
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.3
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
