formatter: "markdown table"

version: ">= 0.16.0"

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: modules

sections:
  show:
    - requirements
    - providers
    - inputs
    - outputs

sort:
  enabled: true
  by: required

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
