---
extends: default
rules:
  document-start:
    present: true
    level: warning
  empty-lines:
    max: 1
    level: warning
  line-length:
    max: 100
    level: warning
  indentation:
    spaces: 2
    level: warning
