---
extends: default
rules:
  document-start:
    present: true
    level: warning
  empty-lines:
    max: 1
    level: warning
  line-length:
    max: 100
    level: warning
  indentation:
    spaces: 2
    level: warning
  trailing-spaces: disable
  comments:
    min-spaces-from-content: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    max-spaces-before: 0
    min-spaces-after: 1
