name: Deploy Order Retrieval Lambda

on:
  push:
    branches:
      - main
    paths:
      - "terraform/states/environments/aws/my-aws-account/eu-west-1/dev-ireland-1/lambda/order-retrieval/lambda_source_code/**"
      - ".github/workflows/order_retrieval_deployments.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Order Retrieval
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_REGION: "eu-west-1"
      ACCOUNT_ID: "${{ vars.AWS_ACCOUNT_ID }}"
      ECR_REPO: "order-retrieval"
      LAMBDA_FUNCTION_NAME: "order-retrieval"
      IMAGE_TAG: "latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/aidoc-devops2-ex-github-oidc-auth
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} \
            ./terraform/states/environments/aws/my-aws-account/${{ env.AWS_REGION }}/dev-ireland-1/lambda/order-retrieval/lambda_source_code
          docker tag ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} \
            ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Push to Amazon ECR
        run: |
          docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --image-uri ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
