name: Deploy Order Retrieval Lambda

on:
  push:
    branches:
      - main
    paths:
      - "terraform/states/environments/aws/my-aws-account/eu-west-1/dev-ireland-1/lambda/order-retrieval/**"
      - ".github/workflows/order_retrieval_deployments.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy Order Retrieval
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_REGION: "eu-west-1"
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO: "order-retrieval"
      LAMBDA_FUNCTION_NAME: "order-retrieval"
      IMAGE_TAG: "latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform & Terragrunt
        run: |
          # Create temp directory
          TEMP_DIR=$(mktemp -d)
          cd $TEMP_DIR
          
          # Download Terraform
          curl -LO https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip
          unzip -o terraform_1.5.5_linux_amd64.zip
          
          # Download Terragrunt
          curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.12/terragrunt_linux_amd64
          
          # Safe removal of existing installations
          sudo rm -f /usr/local/bin/terraform /usr/local/bin/terragrunt
          
          # Install binaries
          sudo install -o root -g root -m 0755 terraform /usr/local/bin/terraform
          sudo install -o root -g root -m 0755 terragrunt_linux_amd64 /usr/local/bin/terragrunt
          
          # Verify installations
          terraform version
          terragrunt --version
          
          # Cleanup
          cd -
          rm -rf $TEMP_DIR

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/aidoc-devops2-ex-github-oidc-auth
          aws-region: ${{ env.AWS_REGION }}

      - name: Assume `github-actions-workflows` Role Securely
        id: assume-role
        run: |
          CREDENTIALS=$(aws sts assume-role \
            --role-arn "arn:aws:iam::${{ env.ACCOUNT_ID }}:role/aidoc-devops2-ex-github-actions-workflows" \
            --role-session-name "GitHubActionsSession")

          # Masking Secrets in Logs
          echo "::add-mask::$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')"
          echo "::add-mask::$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')"
          echo "::add-mask::$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')"

          # Export Variables Securely
          echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} \
            ./terraform/states/environments/aws/my-aws-account/${{ env.AWS_REGION }}/dev-ireland-1/lambda/order-retrieval/lambda_source_code
          docker tag ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} \
            ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Retrieve Latest ECR Image Digest
        id: get-ecr-digest
        run: |
          IMAGE_DIGEST=$(aws ecr describe-images \
            --repository-name ${{ env.ECR_REPO }} \
            --region ${{ env.AWS_REGION }} \
            --query "sort_by(imageDetails,& imagePushedAt)[-1].imageDigest" \
            --output text)

          echo "ECR_IMAGE_DIGEST=${IMAGE_DIGEST}" >> $GITHUB_ENV
          echo "IMAGE_URI=${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}@${IMAGE_DIGEST}" >> $GITHUB_ENV
          echo "Image Digest: ${IMAGE_DIGEST}"

      - name: Assume Terraform State Access Role
        id: assume-state-role
        run: |
          STATE_CREDENTIALS=$(aws sts assume-role \
            --role-arn "arn:aws:iam::${{ env.ACCOUNT_ID }}:role/aidoc-devops2-ex-state-manager" \
            --role-session-name "TerraformStateAccess")
          
          # Store original credentials
          echo "ORIGINAL_AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "ORIGINAL_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "ORIGINAL_AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $GITHUB_ENV
          
          # Set state access credentials
          echo "AWS_ACCESS_KEY_ID=$(echo $STATE_CREDENTIALS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $STATE_CREDENTIALS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $STATE_CREDENTIALS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

      - name: Validate Terraform Code
        working-directory: terraform/states/environments/aws/my-aws-account/eu-west-1/dev-ireland-1/lambda/order-retrieval/
        run: |
          terragrunt run-all validate --terragrunt-non-interactive --terragrunt-include-external-dependencies
          
      # After state operations, restore original credentials
      - name: Restore Original Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=$ORIGINAL_AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$ORIGINAL_AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$ORIGINAL_AWS_SESSION_TOKEN" >> $GITHUB_ENV

      - name: Validate Terraform Code
        working-directory: terraform/states/environments/aws/my-aws-account/eu-west-1/dev-ireland-1/lambda/order-retrieval/
        run: |
          find . -type f -name providers.tf | xargs cat
          export TERRAGRUNT_DISABLE_BUCKET_UPDATE=true
          terragrunt run-all validate --terragrunt-non-interactive

      - name: Update Terragrunt Configuration
        working-directory: terraform/states/environments/aws/my-aws-account/eu-west-1/dev-ireland-1/lambda/order-retrieval/
        run: |
          sed -i "s|image_uri = .*|image_uri = \"${{ env.IMAGE_URI }}\"|" terragrunt.hcl
          cat terragrunt.hcl

      - name: Apply Terraform Changes with Terragrunt
        working-directory: terraform/states/environments/aws/my-aws-account/eu-west-1/dev-ireland-1/lambda/order-retrieval/
        run: |
          terragrunt run-all apply --auto-approve
