---
name: Test Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Test Workflow
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "eu-west-1"
      ACCOUNT_ID: secrets.AWS_ACCOUNT_ID
      ECR_REPO: "order-retrieval"
      LAMBDA_FUNCTION_NAME: "order-retrieval"
      IMAGE_TAG: "latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for OIDC Auth Role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aidoc-devops2-ex-github-oidc-auth
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify OIDC Auth Role
        run: aws sts get-caller-identity

      - name: Assume `github-actions-workflows` Role Securely
        id: assume-role
        run: |
          CREDENTIALS=$(aws sts assume-role \
            --role-arn "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aidoc-devops2-ex-github-actions-workflows" \
            --role-session-name "GitHubActionsSession")

          # Masking Secrets in Logs
          echo "::add-mask::$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')"
          echo "::add-mask::$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')"
          echo "::add-mask::$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')"

          # Export Variables Securely
          echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

      - name: Verify `github-actions-workflows` Role
        run: aws sts get-caller-identity

      - name: Test
        run: |
          echo "$PWD"
          apt update
          apt install -y jq
          apt install -y tree
          tree -f .
          echo "AWS_ACCOUNT_ID: $ACCOUNT_ID"
