name: Test GitHub Actions Credentials

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for OIDC Auth Role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::912466608750:role/aidoc-devops2-ex-github-oidc-auth
          aws-region: eu-north-1

      - name: Verify OIDC Auth Role
        run: aws sts get-caller-identity

      - name: Assume `github-actions-workflows` Role
        id: assume-role
        run: |
          CREDENTIALS=$(aws sts assume-role \
            --role-arn "arn:aws:iam::912466608750:role/aidoc-devops2-ex-github-actions-workflows" \
            --role-session-name "GitHubActionsSession")

          echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

      - name: Verify `github-actions-workflows` Role
        run: aws sts get-caller-identity
